/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssignCommentBean from './AssignCommentBean';
import PushPublishBean from './PushPublishBean';

/**
 * The AdditionalParamsBean model module.
 * @module model/AdditionalParamsBean
 * @version 3
 */
class AdditionalParamsBean {
    /**
     * Constructs a new <code>AdditionalParamsBean</code>.
     * @alias module:model/AdditionalParamsBean
     */
    constructor() { 
        
        AdditionalParamsBean.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdditionalParamsBean</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdditionalParamsBean} obj Optional instance to populate.
     * @return {module:model/AdditionalParamsBean} The populated <code>AdditionalParamsBean</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdditionalParamsBean();

            if (data.hasOwnProperty('pushPublish')) {
                obj['pushPublish'] = PushPublishBean.constructFromObject(data['pushPublish']);
            }
            if (data.hasOwnProperty('assignComment')) {
                obj['assignComment'] = AssignCommentBean.constructFromObject(data['assignComment']);
            }
            if (data.hasOwnProperty('additionalParamsMap')) {
                obj['additionalParamsMap'] = ApiClient.convertToType(data['additionalParamsMap'], {'String': Object});
            }
            if (data.hasOwnProperty('pushPublishBean')) {
                obj['pushPublishBean'] = PushPublishBean.constructFromObject(data['pushPublishBean']);
            }
            if (data.hasOwnProperty('assignCommentBean')) {
                obj['assignCommentBean'] = AssignCommentBean.constructFromObject(data['assignCommentBean']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AdditionalParamsBean</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AdditionalParamsBean</code>.
     */
    static validateJSON(data) {
        // validate the optional field `pushPublish`
        if (data['pushPublish']) { // data not null
          PushPublishBean.validateJSON(data['pushPublish']);
        }
        // validate the optional field `assignComment`
        if (data['assignComment']) { // data not null
          AssignCommentBean.validateJSON(data['assignComment']);
        }
        // validate the optional field `pushPublishBean`
        if (data['pushPublishBean']) { // data not null
          PushPublishBean.validateJSON(data['pushPublishBean']);
        }
        // validate the optional field `assignCommentBean`
        if (data['assignCommentBean']) { // data not null
          AssignCommentBean.validateJSON(data['assignCommentBean']);
        }

        return true;
    }


}



/**
 * @member {module:model/PushPublishBean} pushPublish
 */
AdditionalParamsBean.prototype['pushPublish'] = undefined;

/**
 * @member {module:model/AssignCommentBean} assignComment
 */
AdditionalParamsBean.prototype['assignComment'] = undefined;

/**
 * @member {Object.<String, Object>} additionalParamsMap
 */
AdditionalParamsBean.prototype['additionalParamsMap'] = undefined;

/**
 * @member {module:model/PushPublishBean} pushPublishBean
 */
AdditionalParamsBean.prototype['pushPublishBean'] = undefined;

/**
 * @member {module:model/AssignCommentBean} assignCommentBean
 */
AdditionalParamsBean.prototype['assignCommentBean'] = undefined;






export default AdditionalParamsBean;

