/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiTokenForm model module.
 * @module model/ApiTokenForm
 * @version 3
 */
class ApiTokenForm {
    /**
     * Constructs a new <code>ApiTokenForm</code>.
     * @alias module:model/ApiTokenForm
     */
    constructor() { 
        
        ApiTokenForm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiTokenForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTokenForm} obj Optional instance to populate.
     * @return {module:model/ApiTokenForm} The populated <code>ApiTokenForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTokenForm();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('tokenId')) {
                obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
            }
            if (data.hasOwnProperty('showRevoked')) {
                obj['showRevoked'] = ApiClient.convertToType(data['showRevoked'], 'Boolean');
            }
            if (data.hasOwnProperty('expirationSeconds')) {
                obj['expirationSeconds'] = ApiClient.convertToType(data['expirationSeconds'], 'Number');
            }
            if (data.hasOwnProperty('network')) {
                obj['network'] = ApiClient.convertToType(data['network'], 'String');
            }
            if (data.hasOwnProperty('claims')) {
                obj['claims'] = ApiClient.convertToType(data['claims'], {'String': Object});
            }
            if (data.hasOwnProperty('shouldBeAdmin')) {
                obj['shouldBeAdmin'] = ApiClient.convertToType(data['shouldBeAdmin'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTokenForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTokenForm</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userId'] && !(typeof data['userId'] === 'string' || data['userId'] instanceof String)) {
            throw new Error("Expected the field `userId` to be a primitive type in the JSON string but got " + data['userId']);
        }
        // ensure the json data is a string
        if (data['tokenId'] && !(typeof data['tokenId'] === 'string' || data['tokenId'] instanceof String)) {
            throw new Error("Expected the field `tokenId` to be a primitive type in the JSON string but got " + data['tokenId']);
        }
        // ensure the json data is a string
        if (data['network'] && !(typeof data['network'] === 'string' || data['network'] instanceof String)) {
            throw new Error("Expected the field `network` to be a primitive type in the JSON string but got " + data['network']);
        }

        return true;
    }


}



/**
 * @member {String} userId
 */
ApiTokenForm.prototype['userId'] = undefined;

/**
 * @member {String} tokenId
 */
ApiTokenForm.prototype['tokenId'] = undefined;

/**
 * @member {Boolean} showRevoked
 */
ApiTokenForm.prototype['showRevoked'] = undefined;

/**
 * @member {Number} expirationSeconds
 */
ApiTokenForm.prototype['expirationSeconds'] = undefined;

/**
 * @member {String} network
 */
ApiTokenForm.prototype['network'] = undefined;

/**
 * @member {Object.<String, Object>} claims
 */
ApiTokenForm.prototype['claims'] = undefined;

/**
 * @member {Boolean} shouldBeAdmin
 */
ApiTokenForm.prototype['shouldBeAdmin'] = undefined;






export default ApiTokenForm;

