/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CategoryView model module.
 * @module model/CategoryView
 * @version 3
 */
class CategoryView {
    /**
     * Constructs a new <code>CategoryView</code>.
     * @alias module:model/CategoryView
     */
    constructor() { 
        
        CategoryView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CategoryView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryView} obj Optional instance to populate.
     * @return {module:model/CategoryView} The populated <code>CategoryView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryView();

            if (data.hasOwnProperty('inode')) {
                obj['inode'] = ApiClient.convertToType(data['inode'], 'String');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = ApiClient.convertToType(data['keywords'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('categoryName')) {
                obj['categoryName'] = ApiClient.convertToType(data['categoryName'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'Number');
            }
            if (data.hasOwnProperty('categoryVelocityVarName')) {
                obj['categoryVelocityVarName'] = ApiClient.convertToType(data['categoryVelocityVarName'], 'String');
            }
            if (data.hasOwnProperty('modDate')) {
                obj['modDate'] = ApiClient.convertToType(data['modDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CategoryView</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CategoryView</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['inode'] && !(typeof data['inode'] === 'string' || data['inode'] instanceof String)) {
            throw new Error("Expected the field `inode` to be a primitive type in the JSON string but got " + data['inode']);
        }
        // ensure the json data is a string
        if (data['parent'] && !(typeof data['parent'] === 'string' || data['parent'] instanceof String)) {
            throw new Error("Expected the field `parent` to be a primitive type in the JSON string but got " + data['parent']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['keywords'] && !(typeof data['keywords'] === 'string' || data['keywords'] instanceof String)) {
            throw new Error("Expected the field `keywords` to be a primitive type in the JSON string but got " + data['keywords']);
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['categoryName'] && !(typeof data['categoryName'] === 'string' || data['categoryName'] instanceof String)) {
            throw new Error("Expected the field `categoryName` to be a primitive type in the JSON string but got " + data['categoryName']);
        }
        // ensure the json data is a string
        if (data['categoryVelocityVarName'] && !(typeof data['categoryVelocityVarName'] === 'string' || data['categoryVelocityVarName'] instanceof String)) {
            throw new Error("Expected the field `categoryVelocityVarName` to be a primitive type in the JSON string but got " + data['categoryVelocityVarName']);
        }

        return true;
    }


}



/**
 * @member {String} inode
 */
CategoryView.prototype['inode'] = undefined;

/**
 * @member {String} parent
 */
CategoryView.prototype['parent'] = undefined;

/**
 * @member {String} description
 */
CategoryView.prototype['description'] = undefined;

/**
 * @member {String} keywords
 */
CategoryView.prototype['keywords'] = undefined;

/**
 * @member {String} key
 */
CategoryView.prototype['key'] = undefined;

/**
 * @member {String} categoryName
 */
CategoryView.prototype['categoryName'] = undefined;

/**
 * @member {Boolean} active
 */
CategoryView.prototype['active'] = undefined;

/**
 * @member {Number} sortOrder
 */
CategoryView.prototype['sortOrder'] = undefined;

/**
 * @member {String} categoryVelocityVarName
 */
CategoryView.prototype['categoryVelocityVarName'] = undefined;

/**
 * @member {Date} modDate
 */
CategoryView.prototype['modDate'] = undefined;






export default CategoryView;

