/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExcludedExperimentListForm model module.
 * @module model/ExcludedExperimentListForm
 * @version 3
 */
class ExcludedExperimentListForm {
    /**
     * Constructs a new <code>ExcludedExperimentListForm</code>.
     * @alias module:model/ExcludedExperimentListForm
     */
    constructor() { 
        
        ExcludedExperimentListForm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExcludedExperimentListForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExcludedExperimentListForm} obj Optional instance to populate.
     * @return {module:model/ExcludedExperimentListForm} The populated <code>ExcludedExperimentListForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExcludedExperimentListForm();

            if (data.hasOwnProperty('exclude')) {
                obj['exclude'] = ApiClient.convertToType(data['exclude'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExcludedExperimentListForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExcludedExperimentListForm</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['exclude'])) {
            throw new Error("Expected the field `exclude` to be an array in the JSON data but got " + data['exclude']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} exclude
 */
ExcludedExperimentListForm.prototype['exclude'] = undefined;






export default ExcludedExperimentListForm;

