/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExportSecretForm model module.
 * @module model/ExportSecretForm
 * @version 3
 */
class ExportSecretForm {
    /**
     * Constructs a new <code>ExportSecretForm</code>.
     * @alias module:model/ExportSecretForm
     * @param password {String} 
     * @param exportAll {Boolean} 
     * @param appKeysBySite {Object.<String, Array.<String>>} 
     */
    constructor(password, exportAll, appKeysBySite) { 
        
        ExportSecretForm.initialize(this, password, exportAll, appKeysBySite);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password, exportAll, appKeysBySite) { 
        obj['password'] = password;
        obj['exportAll'] = exportAll;
        obj['appKeysBySite'] = appKeysBySite;
    }

    /**
     * Constructs a <code>ExportSecretForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExportSecretForm} obj Optional instance to populate.
     * @return {module:model/ExportSecretForm} The populated <code>ExportSecretForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportSecretForm();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('exportAll')) {
                obj['exportAll'] = ApiClient.convertToType(data['exportAll'], 'Boolean');
            }
            if (data.hasOwnProperty('appKeys')) {
                obj['appKeys'] = ApiClient.convertToType(data['appKeys'], {'String': ['String']});
            }
            if (data.hasOwnProperty('appKeysBySite')) {
                obj['appKeysBySite'] = ApiClient.convertToType(data['appKeysBySite'], {'String': ['String']});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExportSecretForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExportSecretForm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExportSecretForm.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

ExportSecretForm.RequiredProperties = ["password", "exportAll", "appKeysBySite"];

/**
 * @member {String} password
 */
ExportSecretForm.prototype['password'] = undefined;

/**
 * @member {Boolean} exportAll
 */
ExportSecretForm.prototype['exportAll'] = undefined;

/**
 * @member {Object.<String, Array.<String>>} appKeys
 */
ExportSecretForm.prototype['appKeys'] = undefined;

/**
 * @member {Object.<String, Array.<String>>} appKeysBySite
 */
ExportSecretForm.prototype['appKeysBySite'] = undefined;






export default ExportSecretForm;

