/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FireActionByNameForm model module.
 * @module model/FireActionByNameForm
 * @version 3
 */
class FireActionByNameForm {
    /**
     * Constructs a new <code>FireActionByNameForm</code>.
     * @alias module:model/FireActionByNameForm
     */
    constructor() { 
        
        FireActionByNameForm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FireActionByNameForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FireActionByNameForm} obj Optional instance to populate.
     * @return {module:model/FireActionByNameForm} The populated <code>FireActionByNameForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FireActionByNameForm();

            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('assign')) {
                obj['assign'] = ApiClient.convertToType(data['assign'], 'String');
            }
            if (data.hasOwnProperty('publishDate')) {
                obj['publishDate'] = ApiClient.convertToType(data['publishDate'], 'String');
            }
            if (data.hasOwnProperty('publishTime')) {
                obj['publishTime'] = ApiClient.convertToType(data['publishTime'], 'String');
            }
            if (data.hasOwnProperty('expireDate')) {
                obj['expireDate'] = ApiClient.convertToType(data['expireDate'], 'String');
            }
            if (data.hasOwnProperty('expireTime')) {
                obj['expireTime'] = ApiClient.convertToType(data['expireTime'], 'String');
            }
            if (data.hasOwnProperty('neverExpire')) {
                obj['neverExpire'] = ApiClient.convertToType(data['neverExpire'], 'String');
            }
            if (data.hasOwnProperty('whereToSend')) {
                obj['whereToSend'] = ApiClient.convertToType(data['whereToSend'], 'String');
            }
            if (data.hasOwnProperty('filterKey')) {
                obj['filterKey'] = ApiClient.convertToType(data['filterKey'], 'String');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('pathToMove')) {
                obj['pathToMove'] = ApiClient.convertToType(data['pathToMove'], 'String');
            }
            if (data.hasOwnProperty('timezoneId')) {
                obj['timezoneId'] = ApiClient.convertToType(data['timezoneId'], 'String');
            }
            if (data.hasOwnProperty('individualPermissions')) {
                obj['individualPermissions'] = ApiClient.convertToType(data['individualPermissions'], {'String': ['String']});
            }
            if (data.hasOwnProperty('actionName')) {
                obj['actionName'] = ApiClient.convertToType(data['actionName'], 'String');
            }
            if (data.hasOwnProperty('iwantTo')) {
                obj['iwantTo'] = ApiClient.convertToType(data['iwantTo'], 'String');
            }
            if (data.hasOwnProperty('contentlet')) {
                obj['contentlet'] = ApiClient.convertToType(data['contentlet'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FireActionByNameForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FireActionByNameForm</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['comments'] && !(typeof data['comments'] === 'string' || data['comments'] instanceof String)) {
            throw new Error("Expected the field `comments` to be a primitive type in the JSON string but got " + data['comments']);
        }
        // ensure the json data is a string
        if (data['assign'] && !(typeof data['assign'] === 'string' || data['assign'] instanceof String)) {
            throw new Error("Expected the field `assign` to be a primitive type in the JSON string but got " + data['assign']);
        }
        // ensure the json data is a string
        if (data['publishDate'] && !(typeof data['publishDate'] === 'string' || data['publishDate'] instanceof String)) {
            throw new Error("Expected the field `publishDate` to be a primitive type in the JSON string but got " + data['publishDate']);
        }
        // ensure the json data is a string
        if (data['publishTime'] && !(typeof data['publishTime'] === 'string' || data['publishTime'] instanceof String)) {
            throw new Error("Expected the field `publishTime` to be a primitive type in the JSON string but got " + data['publishTime']);
        }
        // ensure the json data is a string
        if (data['expireDate'] && !(typeof data['expireDate'] === 'string' || data['expireDate'] instanceof String)) {
            throw new Error("Expected the field `expireDate` to be a primitive type in the JSON string but got " + data['expireDate']);
        }
        // ensure the json data is a string
        if (data['expireTime'] && !(typeof data['expireTime'] === 'string' || data['expireTime'] instanceof String)) {
            throw new Error("Expected the field `expireTime` to be a primitive type in the JSON string but got " + data['expireTime']);
        }
        // ensure the json data is a string
        if (data['neverExpire'] && !(typeof data['neverExpire'] === 'string' || data['neverExpire'] instanceof String)) {
            throw new Error("Expected the field `neverExpire` to be a primitive type in the JSON string but got " + data['neverExpire']);
        }
        // ensure the json data is a string
        if (data['whereToSend'] && !(typeof data['whereToSend'] === 'string' || data['whereToSend'] instanceof String)) {
            throw new Error("Expected the field `whereToSend` to be a primitive type in the JSON string but got " + data['whereToSend']);
        }
        // ensure the json data is a string
        if (data['filterKey'] && !(typeof data['filterKey'] === 'string' || data['filterKey'] instanceof String)) {
            throw new Error("Expected the field `filterKey` to be a primitive type in the JSON string but got " + data['filterKey']);
        }
        // ensure the json data is a string
        if (data['query'] && !(typeof data['query'] === 'string' || data['query'] instanceof String)) {
            throw new Error("Expected the field `query` to be a primitive type in the JSON string but got " + data['query']);
        }
        // ensure the json data is a string
        if (data['pathToMove'] && !(typeof data['pathToMove'] === 'string' || data['pathToMove'] instanceof String)) {
            throw new Error("Expected the field `pathToMove` to be a primitive type in the JSON string but got " + data['pathToMove']);
        }
        // ensure the json data is a string
        if (data['timezoneId'] && !(typeof data['timezoneId'] === 'string' || data['timezoneId'] instanceof String)) {
            throw new Error("Expected the field `timezoneId` to be a primitive type in the JSON string but got " + data['timezoneId']);
        }
        // ensure the json data is a string
        if (data['actionName'] && !(typeof data['actionName'] === 'string' || data['actionName'] instanceof String)) {
            throw new Error("Expected the field `actionName` to be a primitive type in the JSON string but got " + data['actionName']);
        }
        // ensure the json data is a string
        if (data['iwantTo'] && !(typeof data['iwantTo'] === 'string' || data['iwantTo'] instanceof String)) {
            throw new Error("Expected the field `iwantTo` to be a primitive type in the JSON string but got " + data['iwantTo']);
        }

        return true;
    }


}



/**
 * @member {String} comments
 */
FireActionByNameForm.prototype['comments'] = undefined;

/**
 * @member {String} assign
 */
FireActionByNameForm.prototype['assign'] = undefined;

/**
 * @member {String} publishDate
 */
FireActionByNameForm.prototype['publishDate'] = undefined;

/**
 * @member {String} publishTime
 */
FireActionByNameForm.prototype['publishTime'] = undefined;

/**
 * @member {String} expireDate
 */
FireActionByNameForm.prototype['expireDate'] = undefined;

/**
 * @member {String} expireTime
 */
FireActionByNameForm.prototype['expireTime'] = undefined;

/**
 * @member {String} neverExpire
 */
FireActionByNameForm.prototype['neverExpire'] = undefined;

/**
 * @member {String} whereToSend
 */
FireActionByNameForm.prototype['whereToSend'] = undefined;

/**
 * @member {String} filterKey
 */
FireActionByNameForm.prototype['filterKey'] = undefined;

/**
 * @member {String} query
 */
FireActionByNameForm.prototype['query'] = undefined;

/**
 * @member {String} pathToMove
 */
FireActionByNameForm.prototype['pathToMove'] = undefined;

/**
 * @member {String} timezoneId
 */
FireActionByNameForm.prototype['timezoneId'] = undefined;

/**
 * @member {Object.<String, Array.<String>>} individualPermissions
 */
FireActionByNameForm.prototype['individualPermissions'] = undefined;

/**
 * @member {String} actionName
 */
FireActionByNameForm.prototype['actionName'] = undefined;

/**
 * @member {String} iwantTo
 */
FireActionByNameForm.prototype['iwantTo'] = undefined;

/**
 * @member {Object.<String, Object>} contentlet
 */
FireActionByNameForm.prototype['contentlet'] = undefined;






export default FireActionByNameForm;

