/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForgotPasswordForm model module.
 * @module model/ForgotPasswordForm
 * @version 3
 */
class ForgotPasswordForm {
    /**
     * Constructs a new <code>ForgotPasswordForm</code>.
     * @alias module:model/ForgotPasswordForm
     * @param userId {String} 
     */
    constructor(userId) { 
        
        ForgotPasswordForm.initialize(this, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId) { 
        obj['userId'] = userId;
    }

    /**
     * Constructs a <code>ForgotPasswordForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForgotPasswordForm} obj Optional instance to populate.
     * @return {module:model/ForgotPasswordForm} The populated <code>ForgotPasswordForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForgotPasswordForm();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForgotPasswordForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForgotPasswordForm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ForgotPasswordForm.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['userId'] && !(typeof data['userId'] === 'string' || data['userId'] instanceof String)) {
            throw new Error("Expected the field `userId` to be a primitive type in the JSON string but got " + data['userId']);
        }

        return true;
    }


}

ForgotPasswordForm.RequiredProperties = ["userId"];

/**
 * @member {String} userId
 */
ForgotPasswordForm.prototype['userId'] = undefined;






export default ForgotPasswordForm;

