/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HostVariable model module.
 * @module model/HostVariable
 * @version 3
 */
class HostVariable {
    /**
     * Constructs a new <code>HostVariable</code>.
     * @alias module:model/HostVariable
     */
    constructor() { 
        
        HostVariable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HostVariable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HostVariable} obj Optional instance to populate.
     * @return {module:model/HostVariable} The populated <code>HostVariable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HostVariable();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('hostId')) {
                obj['hostId'] = ApiClient.convertToType(data['hostId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('lastModifierId')) {
                obj['lastModifierId'] = ApiClient.convertToType(data['lastModifierId'], 'String');
            }
            if (data.hasOwnProperty('lastModDate')) {
                obj['lastModDate'] = ApiClient.convertToType(data['lastModDate'], 'Date');
            }
            if (data.hasOwnProperty('map')) {
                obj['map'] = ApiClient.convertToType(data['map'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HostVariable</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HostVariable</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['hostId'] && !(typeof data['hostId'] === 'string' || data['hostId'] instanceof String)) {
            throw new Error("Expected the field `hostId` to be a primitive type in the JSON string but got " + data['hostId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['lastModifierId'] && !(typeof data['lastModifierId'] === 'string' || data['lastModifierId'] instanceof String)) {
            throw new Error("Expected the field `lastModifierId` to be a primitive type in the JSON string but got " + data['lastModifierId']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
HostVariable.prototype['id'] = undefined;

/**
 * @member {String} hostId
 */
HostVariable.prototype['hostId'] = undefined;

/**
 * @member {String} name
 */
HostVariable.prototype['name'] = undefined;

/**
 * @member {String} key
 */
HostVariable.prototype['key'] = undefined;

/**
 * @member {String} value
 */
HostVariable.prototype['value'] = undefined;

/**
 * @member {String} lastModifierId
 */
HostVariable.prototype['lastModifierId'] = undefined;

/**
 * @member {Date} lastModDate
 */
HostVariable.prototype['lastModDate'] = undefined;

/**
 * @member {Object.<String, Object>} map
 */
HostVariable.prototype['map'] = undefined;






export default HostVariable;

