/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginAsForm model module.
 * @module model/LoginAsForm
 * @version 3
 */
class LoginAsForm {
    /**
     * Constructs a new <code>LoginAsForm</code>.
     * @alias module:model/LoginAsForm
     * @param userId {String} 
     * @param password {String} 
     */
    constructor(userId, password) { 
        
        LoginAsForm.initialize(this, userId, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, password) { 
        obj['userId'] = userId;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>LoginAsForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginAsForm} obj Optional instance to populate.
     * @return {module:model/LoginAsForm} The populated <code>LoginAsForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginAsForm();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoginAsForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LoginAsForm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LoginAsForm.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['userId'] && !(typeof data['userId'] === 'string' || data['userId'] instanceof String)) {
            throw new Error("Expected the field `userId` to be a primitive type in the JSON string but got " + data['userId']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

LoginAsForm.RequiredProperties = ["userId", "password"];

/**
 * @member {String} userId
 */
LoginAsForm.prototype['userId'] = undefined;

/**
 * @member {String} password
 */
LoginAsForm.prototype['password'] = undefined;






export default LoginAsForm;

