/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParameterModel from './ParameterModel';

/**
 * The RestRuleAction model module.
 * @module model/RestRuleAction
 * @version 3
 */
class RestRuleAction {
    /**
     * Constructs a new <code>RestRuleAction</code>.
     * @alias module:model/RestRuleAction
     * @param owningRule {String} 
     * @param actionlet {String} 
     */
    constructor(owningRule, actionlet) { 
        
        RestRuleAction.initialize(this, owningRule, actionlet);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, owningRule, actionlet) { 
        obj['owningRule'] = owningRule;
        obj['actionlet'] = actionlet;
    }

    /**
     * Constructs a <code>RestRuleAction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestRuleAction} obj Optional instance to populate.
     * @return {module:model/RestRuleAction} The populated <code>RestRuleAction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestRuleAction();

            if (data.hasOwnProperty('owningRule')) {
                obj['owningRule'] = ApiClient.convertToType(data['owningRule'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('actionlet')) {
                obj['actionlet'] = ApiClient.convertToType(data['actionlet'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], {'String': ParameterModel});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestRuleAction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestRuleAction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RestRuleAction.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['owningRule'] && !(typeof data['owningRule'] === 'string' || data['owningRule'] instanceof String)) {
            throw new Error("Expected the field `owningRule` to be a primitive type in the JSON string but got " + data['owningRule']);
        }
        // ensure the json data is a string
        if (data['actionlet'] && !(typeof data['actionlet'] === 'string' || data['actionlet'] instanceof String)) {
            throw new Error("Expected the field `actionlet` to be a primitive type in the JSON string but got " + data['actionlet']);
        }

        return true;
    }


}

RestRuleAction.RequiredProperties = ["owningRule", "actionlet"];

/**
 * @member {String} owningRule
 */
RestRuleAction.prototype['owningRule'] = undefined;

/**
 * @member {Number} priority
 */
RestRuleAction.prototype['priority'] = undefined;

/**
 * @member {String} actionlet
 */
RestRuleAction.prototype['actionlet'] = undefined;

/**
 * @member {Object.<String, module:model/ParameterModel>} parameters
 */
RestRuleAction.prototype['parameters'] = undefined;






export default RestRuleAction;

