/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RoleLayoutForm model module.
 * @module model/RoleLayoutForm
 * @version 3
 */
class RoleLayoutForm {
    /**
     * Constructs a new <code>RoleLayoutForm</code>.
     * @alias module:model/RoleLayoutForm
     */
    constructor() { 
        
        RoleLayoutForm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RoleLayoutForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleLayoutForm} obj Optional instance to populate.
     * @return {module:model/RoleLayoutForm} The populated <code>RoleLayoutForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleLayoutForm();

            if (data.hasOwnProperty('roleId')) {
                obj['roleId'] = ApiClient.convertToType(data['roleId'], 'String');
            }
            if (data.hasOwnProperty('layoutIds')) {
                obj['layoutIds'] = ApiClient.convertToType(data['layoutIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RoleLayoutForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RoleLayoutForm</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['roleId'] && !(typeof data['roleId'] === 'string' || data['roleId'] instanceof String)) {
            throw new Error("Expected the field `roleId` to be a primitive type in the JSON string but got " + data['roleId']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['layoutIds'])) {
            throw new Error("Expected the field `layoutIds` to be an array in the JSON data but got " + data['layoutIds']);
        }

        return true;
    }


}



/**
 * @member {String} roleId
 */
RoleLayoutForm.prototype['roleId'] = undefined;

/**
 * @member {Array.<String>} layoutIds
 */
RoleLayoutForm.prototype['layoutIds'] = undefined;






export default RoleLayoutForm;

