/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SmallRoleView model module.
 * @module model/SmallRoleView
 * @version 3
 */
class SmallRoleView {
    /**
     * Constructs a new <code>SmallRoleView</code>.
     * @alias module:model/SmallRoleView
     */
    constructor() { 
        
        SmallRoleView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SmallRoleView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SmallRoleView} obj Optional instance to populate.
     * @return {module:model/SmallRoleView} The populated <code>SmallRoleView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmallRoleView();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('roleKey')) {
                obj['roleKey'] = ApiClient.convertToType(data['roleKey'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SmallRoleView</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SmallRoleView</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['roleKey'] && !(typeof data['roleKey'] === 'string' || data['roleKey'] instanceof String)) {
            throw new Error("Expected the field `roleKey` to be a primitive type in the JSON string but got " + data['roleKey']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
SmallRoleView.prototype['name'] = undefined;

/**
 * @member {String} id
 */
SmallRoleView.prototype['id'] = undefined;

/**
 * @member {String} roleKey
 */
SmallRoleView.prototype['roleKey'] = undefined;

/**
 * @member {Boolean} user
 */
SmallRoleView.prototype['user'] = undefined;






export default SmallRoleView;

