/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tuple2SystemActionString model module.
 * @module model/Tuple2SystemActionString
 * @version 3
 */
class Tuple2SystemActionString {
    /**
     * Constructs a new <code>Tuple2SystemActionString</code>.
     * @alias module:model/Tuple2SystemActionString
     */
    constructor() { 
        
        Tuple2SystemActionString.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tuple2SystemActionString</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tuple2SystemActionString} obj Optional instance to populate.
     * @return {module:model/Tuple2SystemActionString} The populated <code>Tuple2SystemActionString</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tuple2SystemActionString();

            if (data.hasOwnProperty('_1')) {
                obj['_1'] = ApiClient.convertToType(data['_1'], 'String');
            }
            if (data.hasOwnProperty('_2')) {
                obj['_2'] = ApiClient.convertToType(data['_2'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Tuple2SystemActionString</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Tuple2SystemActionString</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['_1'] && !(typeof data['_1'] === 'string' || data['_1'] instanceof String)) {
            throw new Error("Expected the field `_1` to be a primitive type in the JSON string but got " + data['_1']);
        }
        // ensure the json data is a string
        if (data['_2'] && !(typeof data['_2'] === 'string' || data['_2'] instanceof String)) {
            throw new Error("Expected the field `_2` to be a primitive type in the JSON string but got " + data['_2']);
        }

        return true;
    }


}



/**
 * @member {module:model/Tuple2SystemActionString.1Enum} _1
 */
Tuple2SystemActionString.prototype['_1'] = undefined;

/**
 * @member {String} _2
 */
Tuple2SystemActionString.prototype['_2'] = undefined;





/**
 * Allowed values for the <code>_1</code> property.
 * @enum {String}
 * @readonly
 */
Tuple2SystemActionString['1Enum'] = {

    /**
     * value: "NEW"
     * @const
     */
    "NEW": "NEW",

    /**
     * value: "EDIT"
     * @const
     */
    "EDIT": "EDIT",

    /**
     * value: "PUBLISH"
     * @const
     */
    "PUBLISH": "PUBLISH",

    /**
     * value: "UNPUBLISH"
     * @const
     */
    "UNPUBLISH": "UNPUBLISH",

    /**
     * value: "ARCHIVE"
     * @const
     */
    "ARCHIVE": "ARCHIVE",

    /**
     * value: "UNARCHIVE"
     * @const
     */
    "UNARCHIVE": "UNARCHIVE",

    /**
     * value: "DELETE"
     * @const
     */
    "DELETE": "DELETE",

    /**
     * value: "DESTROY"
     * @const
     */
    "DESTROY": "DESTROY"
};



export default Tuple2SystemActionString;

