/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpgradeTaskForm model module.
 * @module model/UpgradeTaskForm
 * @version 3
 */
class UpgradeTaskForm {
    /**
     * Constructs a new <code>UpgradeTaskForm</code>.
     * @alias module:model/UpgradeTaskForm
     * @param upgradeTaskClass {String} 
     */
    constructor(upgradeTaskClass) { 
        
        UpgradeTaskForm.initialize(this, upgradeTaskClass);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, upgradeTaskClass) { 
        obj['upgradeTaskClass'] = upgradeTaskClass;
    }

    /**
     * Constructs a <code>UpgradeTaskForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpgradeTaskForm} obj Optional instance to populate.
     * @return {module:model/UpgradeTaskForm} The populated <code>UpgradeTaskForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpgradeTaskForm();

            if (data.hasOwnProperty('upgradeTaskClass')) {
                obj['upgradeTaskClass'] = ApiClient.convertToType(data['upgradeTaskClass'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpgradeTaskForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpgradeTaskForm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpgradeTaskForm.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['upgradeTaskClass'] && !(typeof data['upgradeTaskClass'] === 'string' || data['upgradeTaskClass'] instanceof String)) {
            throw new Error("Expected the field `upgradeTaskClass` to be a primitive type in the JSON string but got " + data['upgradeTaskClass']);
        }

        return true;
    }


}

UpgradeTaskForm.RequiredProperties = ["upgradeTaskClass"];

/**
 * @member {String} upgradeTaskClass
 */
UpgradeTaskForm.prototype['upgradeTaskClass'] = undefined;






export default UpgradeTaskForm;

