/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserTimeZone model module.
 * @module model/UserTimeZone
 * @version 3
 */
class UserTimeZone {
    /**
     * Constructs a new <code>UserTimeZone</code>.
     * @alias module:model/UserTimeZone
     */
    constructor() { 
        
        UserTimeZone.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserTimeZone</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserTimeZone} obj Optional instance to populate.
     * @return {module:model/UserTimeZone} The populated <code>UserTimeZone</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserTimeZone();

            if (data.hasOwnProperty('rawOffset')) {
                obj['rawOffset'] = ApiClient.convertToType(data['rawOffset'], 'Number');
            }
            if (data.hasOwnProperty('dstsavings')) {
                obj['dstsavings'] = ApiClient.convertToType(data['dstsavings'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserTimeZone</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserTimeZone</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['displayName'] && !(typeof data['displayName'] === 'string' || data['displayName'] instanceof String)) {
            throw new Error("Expected the field `displayName` to be a primitive type in the JSON string but got " + data['displayName']);
        }

        return true;
    }


}



/**
 * @member {Number} rawOffset
 */
UserTimeZone.prototype['rawOffset'] = undefined;

/**
 * @member {Number} dstsavings
 */
UserTimeZone.prototype['dstsavings'] = undefined;

/**
 * @member {String} id
 */
UserTimeZone.prototype['id'] = undefined;

/**
 * @member {String} displayName
 */
UserTimeZone.prototype['displayName'] = undefined;






export default UserTimeZone;

