/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkflowStepAddForm model module.
 * @module model/WorkflowStepAddForm
 * @version 3
 */
class WorkflowStepAddForm {
    /**
     * Constructs a new <code>WorkflowStepAddForm</code>.
     * @alias module:model/WorkflowStepAddForm
     * @param schemeId {String} 
     * @param stepName {String} 
     * @param enableEscalation {Boolean} 
     * @param escalationAction {String} 
     * @param escalationTime {String} 
     * @param stepResolved {Boolean} 
     */
    constructor(schemeId, stepName, enableEscalation, escalationAction, escalationTime, stepResolved) { 
        
        WorkflowStepAddForm.initialize(this, schemeId, stepName, enableEscalation, escalationAction, escalationTime, stepResolved);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, schemeId, stepName, enableEscalation, escalationAction, escalationTime, stepResolved) { 
        obj['schemeId'] = schemeId;
        obj['stepName'] = stepName;
        obj['enableEscalation'] = enableEscalation;
        obj['escalationAction'] = escalationAction;
        obj['escalationTime'] = escalationTime;
        obj['stepResolved'] = stepResolved;
    }

    /**
     * Constructs a <code>WorkflowStepAddForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowStepAddForm} obj Optional instance to populate.
     * @return {module:model/WorkflowStepAddForm} The populated <code>WorkflowStepAddForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowStepAddForm();

            if (data.hasOwnProperty('schemeId')) {
                obj['schemeId'] = ApiClient.convertToType(data['schemeId'], 'String');
            }
            if (data.hasOwnProperty('stepName')) {
                obj['stepName'] = ApiClient.convertToType(data['stepName'], 'String');
            }
            if (data.hasOwnProperty('enableEscalation')) {
                obj['enableEscalation'] = ApiClient.convertToType(data['enableEscalation'], 'Boolean');
            }
            if (data.hasOwnProperty('escalationAction')) {
                obj['escalationAction'] = ApiClient.convertToType(data['escalationAction'], 'String');
            }
            if (data.hasOwnProperty('escalationTime')) {
                obj['escalationTime'] = ApiClient.convertToType(data['escalationTime'], 'String');
            }
            if (data.hasOwnProperty('stepResolved')) {
                obj['stepResolved'] = ApiClient.convertToType(data['stepResolved'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowStepAddForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowStepAddForm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkflowStepAddForm.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['schemeId'] && !(typeof data['schemeId'] === 'string' || data['schemeId'] instanceof String)) {
            throw new Error("Expected the field `schemeId` to be a primitive type in the JSON string but got " + data['schemeId']);
        }
        // ensure the json data is a string
        if (data['stepName'] && !(typeof data['stepName'] === 'string' || data['stepName'] instanceof String)) {
            throw new Error("Expected the field `stepName` to be a primitive type in the JSON string but got " + data['stepName']);
        }
        // ensure the json data is a string
        if (data['escalationAction'] && !(typeof data['escalationAction'] === 'string' || data['escalationAction'] instanceof String)) {
            throw new Error("Expected the field `escalationAction` to be a primitive type in the JSON string but got " + data['escalationAction']);
        }
        // ensure the json data is a string
        if (data['escalationTime'] && !(typeof data['escalationTime'] === 'string' || data['escalationTime'] instanceof String)) {
            throw new Error("Expected the field `escalationTime` to be a primitive type in the JSON string but got " + data['escalationTime']);
        }

        return true;
    }


}

WorkflowStepAddForm.RequiredProperties = ["schemeId", "stepName", "enableEscalation", "escalationAction", "escalationTime", "stepResolved"];

/**
 * @member {String} schemeId
 */
WorkflowStepAddForm.prototype['schemeId'] = undefined;

/**
 * @member {String} stepName
 */
WorkflowStepAddForm.prototype['stepName'] = undefined;

/**
 * @member {Boolean} enableEscalation
 */
WorkflowStepAddForm.prototype['enableEscalation'] = undefined;

/**
 * @member {String} escalationAction
 */
WorkflowStepAddForm.prototype['escalationAction'] = undefined;

/**
 * @member {String} escalationTime
 */
WorkflowStepAddForm.prototype['escalationTime'] = undefined;

/**
 * @member {Boolean} stepResolved
 */
WorkflowStepAddForm.prototype['stepResolved'] = undefined;






export default WorkflowStepAddForm;

