/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkflowReorderWorkflowActionStepForm model module.
 * @module model/WorkflowReorderWorkflowActionStepForm
 * @version 3
 */
class WorkflowReorderWorkflowActionStepForm {
    /**
     * Constructs a new <code>WorkflowReorderWorkflowActionStepForm</code>.
     * @alias module:model/WorkflowReorderWorkflowActionStepForm
     * @param order {Number} 
     */
    constructor(order) { 
        
        WorkflowReorderWorkflowActionStepForm.initialize(this, order);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, order) { 
        obj['order'] = order;
    }

    /**
     * Constructs a <code>WorkflowReorderWorkflowActionStepForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowReorderWorkflowActionStepForm} obj Optional instance to populate.
     * @return {module:model/WorkflowReorderWorkflowActionStepForm} The populated <code>WorkflowReorderWorkflowActionStepForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowReorderWorkflowActionStepForm();

            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowReorderWorkflowActionStepForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowReorderWorkflowActionStepForm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkflowReorderWorkflowActionStepForm.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

WorkflowReorderWorkflowActionStepForm.RequiredProperties = ["order"];

/**
 * @member {Number} order
 */
WorkflowReorderWorkflowActionStepForm.prototype['order'] = undefined;






export default WorkflowReorderWorkflowActionStepForm;

