/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DotCmsRestApi);
  }
}(this, function(expect, DotCmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DotCmsRestApi.CopySiteForm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CopySiteForm', function() {
    it('should create an instance of CopySiteForm', function() {
      // uncomment below and update the code to test CopySiteForm
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be.a(DotCmsRestApi.CopySiteForm);
    });

    it('should have the property copyFromSiteId (base name: "copyFromSiteId")', function() {
      // uncomment below and update the code to test the property copyFromSiteId
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property copyAll (base name: "copyAll")', function() {
      // uncomment below and update the code to test the property copyAll
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property copyTemplatesContainers (base name: "copyTemplatesContainers")', function() {
      // uncomment below and update the code to test the property copyTemplatesContainers
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property copyContentOnPages (base name: "copyContentOnPages")', function() {
      // uncomment below and update the code to test the property copyContentOnPages
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property copyFolders (base name: "copyFolders")', function() {
      // uncomment below and update the code to test the property copyFolders
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property copyContentOnSite (base name: "copyContentOnSite")', function() {
      // uncomment below and update the code to test the property copyContentOnSite
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property copyLinks (base name: "copyLinks")', function() {
      // uncomment below and update the code to test the property copyLinks
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property copySiteVariables (base name: "copySiteVariables")', function() {
      // uncomment below and update the code to test the property copySiteVariables
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

    it('should have the property site (base name: "site")', function() {
      // uncomment below and update the code to test the property site
      //var instance = new DotCmsRestApi.CopySiteForm();
      //expect(instance).to.be();
    });

  });

}));
