/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DotCmsRestApi);
  }
}(this, function(expect, DotCmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DotCmsRestApi.FireBulkActionsForm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FireBulkActionsForm', function() {
    it('should create an instance of FireBulkActionsForm', function() {
      // uncomment below and update the code to test FireBulkActionsForm
      //var instance = new DotCmsRestApi.FireBulkActionsForm();
      //expect(instance).to.be.a(DotCmsRestApi.FireBulkActionsForm);
    });

    it('should have the property query (base name: "query")', function() {
      // uncomment below and update the code to test the property query
      //var instance = new DotCmsRestApi.FireBulkActionsForm();
      //expect(instance).to.be();
    });

    it('should have the property contentletIds (base name: "contentletIds")', function() {
      // uncomment below and update the code to test the property contentletIds
      //var instance = new DotCmsRestApi.FireBulkActionsForm();
      //expect(instance).to.be();
    });

    it('should have the property workflowActionId (base name: "workflowActionId")', function() {
      // uncomment below and update the code to test the property workflowActionId
      //var instance = new DotCmsRestApi.FireBulkActionsForm();
      //expect(instance).to.be();
    });

    it('should have the property additionalParams (base name: "additionalParams")', function() {
      // uncomment below and update the code to test the property additionalParams
      //var instance = new DotCmsRestApi.FireBulkActionsForm();
      //expect(instance).to.be();
    });

    it('should have the property popupParamsBean (base name: "popupParamsBean")', function() {
      // uncomment below and update the code to test the property popupParamsBean
      //var instance = new DotCmsRestApi.FireBulkActionsForm();
      //expect(instance).to.be();
    });

  });

}));
