/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DotCmsRestApi);
  }
}(this, function(expect, DotCmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DotCmsRestApi.PageForm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PageForm', function() {
    it('should create an instance of PageForm', function() {
      // uncomment below and update the code to test PageForm
      //var instance = new DotCmsRestApi.PageForm();
      //expect(instance).to.be.a(DotCmsRestApi.PageForm);
    });

    it('should have the property themeId (base name: "themeId")', function() {
      // uncomment below and update the code to test the property themeId
      //var instance = new DotCmsRestApi.PageForm();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new DotCmsRestApi.PageForm();
      //expect(instance).to.be();
    });

    it('should have the property hostId (base name: "hostId")', function() {
      // uncomment below and update the code to test the property hostId
      //var instance = new DotCmsRestApi.PageForm();
      //expect(instance).to.be();
    });

    it('should have the property layout (base name: "layout")', function() {
      // uncomment below and update the code to test the property layout
      //var instance = new DotCmsRestApi.PageForm();
      //expect(instance).to.be();
    });

    it('should have the property anonymousLayout (base name: "anonymousLayout")', function() {
      // uncomment below and update the code to test the property anonymousLayout
      //var instance = new DotCmsRestApi.PageForm();
      //expect(instance).to.be();
    });

  });

}));
