/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DotCmsRestApi);
  }
}(this, function(expect, DotCmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DotCmsRestApi.SiteVariableView();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SiteVariableView', function() {
    it('should create an instance of SiteVariableView', function() {
      // uncomment below and update the code to test SiteVariableView
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be.a(DotCmsRestApi.SiteVariableView);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

    it('should have the property hostId (base name: "hostId")', function() {
      // uncomment below and update the code to test the property hostId
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

    it('should have the property lastModifierId (base name: "lastModifierId")', function() {
      // uncomment below and update the code to test the property lastModifierId
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

    it('should have the property lastModDate (base name: "lastModDate")', function() {
      // uncomment below and update the code to test the property lastModDate
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

    it('should have the property lastModifierFullName (base name: "lastModifierFullName")', function() {
      // uncomment below and update the code to test the property lastModifierFullName
      //var instance = new DotCmsRestApi.SiteVariableView();
      //expect(instance).to.be();
    });

  });

}));
