/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DotCmsRestApi);
  }
}(this, function(expect, DotCmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DotCmsRestApi.TemplateLayout();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplateLayout', function() {
    it('should create an instance of TemplateLayout', function() {
      // uncomment below and update the code to test TemplateLayout
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be.a(DotCmsRestApi.TemplateLayout);
    });

    it('should have the property width (base name: "width")', function() {
      // uncomment below and update the code to test the property width
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be();
    });

    it('should have the property header (base name: "header")', function() {
      // uncomment below and update the code to test the property header
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be();
    });

    it('should have the property footer (base name: "footer")', function() {
      // uncomment below and update the code to test the property footer
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be();
    });

    it('should have the property sidebar (base name: "sidebar")', function() {
      // uncomment below and update the code to test the property sidebar
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be();
    });

    it('should have the property bodyRows (base name: "bodyRows")', function() {
      // uncomment below and update the code to test the property bodyRows
      //var instance = new DotCmsRestApi.TemplateLayout();
      //expect(instance).to.be();
    });

  });

}));
