/**
 * dotCMS REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DotCmsRestApi);
  }
}(this, function(expect, DotCmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DotCmsRestApi.WorkflowActionForm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WorkflowActionForm', function() {
    it('should create an instance of WorkflowActionForm', function() {
      // uncomment below and update the code to test WorkflowActionForm
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be.a(DotCmsRestApi.WorkflowActionForm);
    });

    it('should have the property actionId (base name: "actionId")', function() {
      // uncomment below and update the code to test the property actionId
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property schemeId (base name: "schemeId")', function() {
      // uncomment below and update the code to test the property schemeId
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property stepId (base name: "stepId")', function() {
      // uncomment below and update the code to test the property stepId
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionName (base name: "actionName")', function() {
      // uncomment below and update the code to test the property actionName
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property whoCanUse (base name: "whoCanUse")', function() {
      // uncomment below and update the code to test the property whoCanUse
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionIcon (base name: "actionIcon")', function() {
      // uncomment below and update the code to test the property actionIcon
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionAssignable (base name: "actionAssignable")', function() {
      // uncomment below and update the code to test the property actionAssignable
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionCommentable (base name: "actionCommentable")', function() {
      // uncomment below and update the code to test the property actionCommentable
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property requiresCheckout (base name: "requiresCheckout")', function() {
      // uncomment below and update the code to test the property requiresCheckout
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property showOn (base name: "showOn")', function() {
      // uncomment below and update the code to test the property showOn
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionRoleHierarchyForAssign (base name: "actionRoleHierarchyForAssign")', function() {
      // uncomment below and update the code to test the property actionRoleHierarchyForAssign
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property roleHierarchyForAssign (base name: "roleHierarchyForAssign")', function() {
      // uncomment below and update the code to test the property roleHierarchyForAssign
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionNextStep (base name: "actionNextStep")', function() {
      // uncomment below and update the code to test the property actionNextStep
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionNextAssign (base name: "actionNextAssign")', function() {
      // uncomment below and update the code to test the property actionNextAssign
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

    it('should have the property actionCondition (base name: "actionCondition")', function() {
      // uncomment below and update the code to test the property actionCondition
      //var instance = new DotCmsRestApi.WorkflowActionForm();
      //expect(instance).to.be();
    });

  });

}));
